//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_titles
    {
        public string title { get; set; }
        public string authors { get; set; }
        public Nullable<short> Pages { get; set; }
        public string pub_name { get; set; }
        public Nullable<int> pub_date { get; set; }
        public byte[] logo { get; set; }
    }
}
